const facts = [
    { fact: "My fav color is purple." },
    { fact: "I like to swim" },
    { fact: "I broke my finger" },
    { fact: "I'm ambidextrous." },
    { fact: "I can say my alphabet backwards" },
    { fact: "I am not famous" },
    { fact: "I was born in Louisiana" },
    { fact: "I have never had a Peanut Butter and Jelly Sandwich!" },
    { fact: "I am allergic to cats" },
    { fact: "I like trains." },
    { fact: "I know the secret identity of beastcarp1" },
    { fact: "I have a dog" },
    { fact: "I hate UNA parking" },
    { fact: "I have 3 dogs" },
    { fact: "I'm adopted from China :D" },
    { fact: "I used to have an orange Hummer H3" },
    { fact: "I play on the rugby team" },
    { fact: "UNA basketball sold the bag" },
    { fact: "The Great Wall of China is 13,000 miles long" },
    { fact: "I hate javascript." },
    { fact: "I love the Bible verse Romans 5:8!" },
    { fact: "I love running." },
    { fact: "I have eaten 1 pound of ground beef every day for the last 6 months." },
    { fact: "Still very less parking space in UNA" },
    { fact: "I enjoy kickboxing" },
    { fact: "classroom user 27" },
    { fact: "classroom user 28" },
    { fact: "Random: I built the Eiffel Tower" },
    
  ];
